package com.lifeflow.security

internal enum class SecurityRuntimeDecisionCode {
    AUTH_CONTEXT_INVALID,
    TRUSTED_BASE_ONLY_REQUIRED,
    TRUST_NOT_SUFFICIENT,
    EMERGENCY_NOT_APPROVED,
    EMERGENCY_WINDOW_EXPIRED,
    EMERGENCY_APPROVAL_REQUIRED,
    STRONGER_AUTH_REQUIRED,
    RECENT_AUTH_REQUIRED,
    COMPROMISED,
    EMERGENCY_REJECTED,
    RECOVERY_REQUIRED,
    EMERGENCY_LIMITED,
    PROTECTED_RUNTIME_BLOCKED,
    AUTH_REQUIRED,
    RESOLVE_EMERGENCY_ACCESS
}
