package com.lifeflow.security

internal enum class SecurityRuntimeContainmentCode {
    ACTIVE_COMPROMISE_SIGNAL,
    TRUST_ALREADY_COMPROMISED,
    FORCE_COMPROMISED_LOCKDOWN,
    RECOVERY_REQUIRED,
    AUTH_FAILURE_BURST,
    POLICY_VIOLATION_BURST,
    RECOMMEND_TRUST_DEGRADE,
    HEIGHTENED_GUARD,
    OBSERVE_ONLY,
    CONTAINMENT_NORMAL,
    CONTAINMENT_GUARDED,
    CONTAINMENT_RESTRICTED,
    CONTAINMENT_RECOVERY_ONLY
}
